const tripImage = (filename) => `/assets/mason-gift-assets/trip-options/${filename}`;

export const tripOptions = [
    {
        id: 'costa-rica',
        country: 'Costa Rica',
        title: 'Hike, Bike & Raft',
        duration: '8 days',
        route: 'San José → Monteverde → La Fortuna → Puerto Viejo → San José',
        image: tripImage('costa-rica.webp'),
        imageAlt: 'Five travelers in yellow helmets paddle a raft through splashing white water in Costa Rica.',
        location: { lat: 9.75, lng: -84.1 },
        focusCountries: ['Costa Rica'],
        markers: [{ lat: 9.75, lng: -84.1, label: 'Costa Rica' }],
        summary: 'A fast, outdoors-first loop through cloud forest, volcano country, jungle river and the Caribbean coast.',
        itinerary: [
            { label: 'Monteverde', detail: 'Walk the cloud forest with a local guide and look for wildlife in the canopy.' },
            { label: 'La Fortuna', detail: 'Take a free day around Arenal for trails, waterfalls or a long soak in the hot springs.' },
            { label: 'Pacuare River', detail: 'Spend the day rafting class III and IV rapids through the rainforest.' },
            { label: 'Puerto Viejo', detail: 'Cycle the coast, swim, and finish with Caribbean flavours before returning to San José.' },
        ],
    },
    {
        id: 'mexico',
        country: 'Mexico',
        title: 'Real Food Adventure',
        duration: '8 days',
        route: 'Mexico City → Puebla → Oaxaca',
        image: tripImage('mexico.webp'),
        imageAlt: 'Travelers laugh while sharing Mexican street food beside a vivid blue wall.',
        location: { lat: 19.43, lng: -99.13 },
        focusCountries: ['Mexico'],
        markers: [{ lat: 19.43, lng: -99.13, label: 'Mexico' }],
        summary: 'An edible route from Mexico City to Oaxaca, built around markets, family traditions, street stalls and regional specialties.',
        itinerary: [
            { label: 'Mexico City', detail: 'Start with a street-food crawl and learn how the capital layers old and new food traditions.' },
            { label: 'San Pedro Tláhuac', detail: 'Explore the chinampas and meet people preserving the area’s agricultural history.' },
            { label: 'Puebla', detail: 'Taste the city’s signature dishes and the stories behind them.' },
            { label: 'Oaxaca', detail: 'Shop the markets, cook with a local chef and make room for mole, chocolate and mezcal.' },
        ],
    },
    {
        id: 'indonesia',
        country: 'Indonesia',
        title: 'Komodo & Flores Adventure',
        duration: '10 days',
        route: 'Kelimutu → Flores → Wae Rebo → Komodo → Labuan Bajo',
        image: tripImage('indonesia.webp'),
        imageAlt: 'Two Komodo dragons wrestle on a grassy hillside above blue water, with a third dragon resting nearby.',
        location: { lat: -8.55, lng: 120.15 },
        focusCountries: ['Indonesia'],
        markers: [{ lat: -8.55, lng: 120.15, label: 'Flores & Komodo' }],
        summary: 'A rugged island crossing with volcanic lakes, mountain villages, wild swimming and two days sailing through Komodo National Park.',
        itinerary: [
            { label: 'Kelimutu', detail: 'Wake before sunrise for the walk to the volcano’s three crater lakes.' },
            { label: 'Across Flores', detail: 'Break up the overland journey with hot springs, rice terraces and small towns.' },
            { label: 'Wae Rebo', detail: 'Hike into the highlands and spend the night in a traditional mountain village.' },
            { label: 'Komodo', detail: 'Sail between islands, snorkel, land on Pink Beach and look for the famous dragons.' },
        ],
    },
    {
        id: 'india',
        country: 'India',
        title: 'Real Food Adventure',
        duration: '13 days',
        route: 'Delhi → Agra → Jaipur → Rural Rajasthan → Mumbai → Goa',
        image: tripImage('india.webp'),
        imageAlt: 'Four travelers smile over bowls of curry in a crowded Indian street-food market.',
        location: { lat: 22.8, lng: 78.9 },
        focusCountries: ['India'],
        markers: [{ lat: 22.8, lng: 78.9, label: 'India' }],
        summary: 'A food-led sweep through North India, Mumbai and Goa—with iconic landmarks included between the very important meals.',
        itinerary: [
            { label: 'Delhi & Agra', detail: 'Eat through Old Delhi, then make the pilgrimage to the Taj Mahal.' },
            { label: 'Jaipur', detail: 'Pair Rajasthani flavours with the Amber Fort and the Palace of the Winds.' },
            { label: 'Rural Rajasthan', detail: 'Stay beyond the major cities for home cooking, farms and a slower side of the region.' },
            { label: 'Mumbai & Goa', detail: 'Move from market snacks and big-city energy to Portuguese-influenced cooking by the coast.' },
        ],
    },
    {
        id: 'nepal',
        country: 'Nepal',
        title: 'Essential Nepal',
        duration: '9 days',
        route: 'Kathmandu → Trisuli River → Pokhara → Annapurna foothills → Kathmandu',
        image: tripImage('nepal.webp'),
        imageAlt: 'A hillside village in Nepal beneath green ridges and towering snow-covered Himalayan peaks.',
        location: { lat: 28.2, lng: 84.0 },
        focusCountries: ['Nepal'],
        markers: [{ lat: 28.2, lng: 84.0, label: 'Nepal' }],
        summary: 'The shorter Nepal option: temples and city life, river rafting, an approachable Himalayan trek and a village homestay.',
        itinerary: [
            { label: 'Kathmandu', detail: 'Begin among the temples, squares and dense street life of the capital.' },
            { label: 'Trisuli River', detail: 'Raft downstream, then settle into a riverside camp for the night.' },
            { label: 'Annapurna foothills', detail: 'Trek through forests and mountain villages with huge Himalayan views.' },
            { label: 'Hemjakot', detail: 'Share a home-cooked dinner and a night with a local family before the return to Kathmandu.' },
        ],
    },
    {
        id: 'everest',
        country: 'Nepal',
        displayCountry: 'Nepal — Everest',
        title: 'Epic Everest Base Camp Trek',
        duration: '15 days',
        route: 'Kathmandu → Lukla → Namche Bazaar → Everest Base Camp → Kathmandu',
        image: tripImage('everest.webp'),
        imageAlt: 'A large group of hikers poses on a rocky Himalayan trail beneath snow-covered peaks in Nepal.',
        location: { lat: 27.99, lng: 86.93 },
        focusCountries: ['Nepal'],
        markers: [{ lat: 27.99, lng: 86.93, label: 'Everest Base Camp' }],
        summary: 'The big one: two weeks in the Himalayas, climbing gradually through Sherpa country to stand at Everest Base Camp.',
        itinerary: [
            { label: 'Lukla', detail: 'Fly into the mountains and begin the slow climb through the Khumbu Valley.' },
            { label: 'Namche Bazaar', detail: 'Acclimatise with tea houses, momos and views that keep getting more ridiculous.' },
            { label: 'High Himalayas', detail: 'Pass monasteries, suspension bridges and increasingly stark mountain landscapes.' },
            { label: 'Base Camp', detail: 'Reach Everest Base Camp with local leaders and porters, then retrace the trail to Kathmandu.' },
        ],
    },
    {
        id: 'jordan',
        country: 'Jordan',
        displayCountry: 'Jordan & Egypt',
        title: 'Jordan & Egypt Express',
        duration: '9 days',
        route: 'Amman → Petra → Wadi Rum → Red Sea → Mt Sinai → Cairo',
        image: tripImage('jordan.webp'),
        imageAlt: 'Two travelers look up at the carved sandstone Treasury set into the cliffs of Petra, Jordan.',
        location: { lat: 29.5, lng: 33.0 },
        focusCountries: ['Jordan', 'Egypt'],
        markers: [
            { lat: 30.33, lng: 35.44, label: 'Petra' },
            { lat: 30.04, lng: 31.24, label: 'Cairo' },
        ],
        summary: 'A compact cross-border epic: Petra, desert stars, the Red Sea, a Sinai sunrise and the pyramids in one very full week.',
        itinerary: [
            { label: 'Petra', detail: 'Walk through the Siq and spend time among the rose-coloured ruins.' },
            { label: 'Wadi Rum', detail: 'Cross the desert and sleep beneath the stars at a Bedouin-style camp.' },
            { label: 'Red Sea & Sinai', detail: 'Head through Aqaba, then climb Mt Sinai and visit St Catherine’s Monastery.' },
            { label: 'Cairo', detail: 'Finish with the pyramids, city souqs and the wonderful chaos of Egypt’s capital.' },
        ],
    },
];
